#!/bin/bash

make main
make countzeros

./runtests boat
./runtests f_16
./runtests gradient
./runtests konye
./runtests lenna
./runtests peppers
./runtests tools
./runtests wheel
cd results && ./buildall && cd ..
rm main
rm countzeros

